name: React CI

on:
  # Déclenche le workflow à chaque push et pull request sur la branche principale
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code du dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Étape 2 : Installer Node.js (choisis la version que tu utilises)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 22.11.0

    # Étape 3 : Installer les dépendances
    - name: Install dependencies
      run: npm install

    # Étape 4 : Compiler le projet
    - name: Build project
      run: npm run build

    # Étape 5 : Lancer les tests
    - name: Run tests
      run: npm test
